idf_component_register(
    SRCS
        "screens.c"
        "ui.c"
        "styles.c"
        "images.c"
        "eez-flow.cpp"
        "eez_wrapper.cpp"
        "ai_hal9000.c"
        "ui_image_50.c"
        "ui_image_80.c"
        "ui_image_ai_asistant.c"
        "ui_image_agent.c"
        "ui_image_charging.c"
        "ui_image_chatbot.c"
        "ui_image_cloud.c"
        "ui_image_cloudy.c"
        "ui_image_cloudy__1_.c"
        "ui_image_cloudy__2_.c"
        "ui_image_foog.c"
        "ui_image_full_battery.c"
        "ui_image_games.c"
        "ui_image_hail.c"
        "ui_image_high_battery.c"
        "ui_image_hum.c"
        "ui_image_info.c"
        "ui_image_music.c"
        "ui_image_microphone.c"
        "ui_image_night.c"
        "ui_image_night__1_.c"
        "ui_image_notes.c"
        "ui_image_pause.c"
        "ui_image_play.c"
        "ui_image_playlist.c"
        "ui_image_plus.c"
        "ui_image_rainy.c"
        "ui_image_rainy__1_.c"
        "ui_image_record_button.c"
        "ui_image_settings.c"
        "ui_image_smart_home.c"
        "ui_image_snowy.c"
        "ui_image_storm.c"
        "ui_image_sun.c"
        "ui_image_therm.c"
        "ui_image_umbrella.c"
        "ui_image_wifi.c"
        "ui_image_infopic.c"
        "ui_image_next.c"
        "ui_image_prev.c"
        "ui_image_living.c"
        "ui_image_kitchen.c"
        "ui_image_temperature.c"
        "ui_image_thread.c"
        "ui_image_matter.c"
        "ui_image_aianim.c"
    INCLUDE_DIRS "." "include"
    REQUIRES esp_lvgl_port
    PRIV_REQUIRES lvgl esp_lvgl_port display encoder freertos esp_timer games
)
