#include "images.h"

const ext_img_desc_t images[33] = {
    { "wifi", &img_wifi },
    { "agent", &img_agent },
    { "settings", &img_settings },
    { "smartHome", &img_smart_home },
    { "games", &img_games },
    { "chatbot", &img_chatbot },
    { "info", &img_info },
    { "50", &img_50 },
    { "80", &img_80 },
    { "charging", &img_charging },
    { "full-battery", &img_full_battery },
    { "high-battery", &img_high_battery },
    { "plus", &img_plus },
    { "cloud", &img_cloud },
    { "cloudy (1)", &img_cloudy__1_ },
    { "cloudy (2)", &img_cloudy__2_ },
    { "cloudy", &img_cloudy },
    { "foog", &img_foog },
    { "hail", &img_hail },
    { "night (1)", &img_night__1_ },
    { "night", &img_night },
    { "rainy (1)", &img_rainy__1_ },
    { "rainy", &img_rainy },
    { "snowy", &img_snowy },
    { "storm", &img_storm },
    { "sun", &img_sun },
    { "umbrella", &img_umbrella },
    { "therm", &img_therm },
    { "hum", &img_hum },
    { "aiAsistant", &img_ai_asistant },
    { "microphone", &img_microphone },
    { "record-button", &img_record_button },
    { "infopic", &img_infopic },
};
